# Generated by Django 5.1.1 on 2024-09-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('description', models.CharField(max_length=555)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='books/')),
            ],
        ),
    ]
